#!/usr/bin/python

Import('env')

import os

# Helper function that prepends directories
# TODO works only for one directory at the moment
def allInDir(dir, files):
    return map(lambda f : os.path.join(dir, f), files)

# List of all source files
sourceFiles = ['main.cpp', 'WavePropagation.cpp']
sourceFiles += allInDir('tools', ['logger.cpp'])

# Add source files to scons env
for f in sourceFiles:
    env.srcFiles.append(env.Object(f))

Export('env')